export const PROVIDERS = {
  USERS: 'USERS_REPOSITORY',
  CATEGORIES: 'CATEGORIES_REPOSITORY',
  TRANSACTIONS: 'TRANSACTIONS_REPOSITORY',
  GOALS: 'GOALS_REPOSITORY',
  WALLETS: 'WALLETS_REPOSITORY',
};
